"use client";

import { RecoilRoot } from "recoil";
import Search from "./components/search";
import "./style/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <RecoilRoot>
        <body>
          <nav className="bg-zinc-300 p-4">
            <Search />
          </nav>
          {children}
        </body>
      </RecoilRoot>
    </html>
  );
}
